name: Publish Gem to GitHub Packages

on:
  push:
    tags:
      - '*'

jobs:
  publish_gem:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install gems
        run: bundle install

      - name: Release
        run: |
          ./release.sh
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
        shell: bash
        env:
          WRITE_GHCR_TOKEN: ${{ secrets.WRITE_GHCR_TOKEN }}